/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
};

export type ClarityChecks = {
  _type: "clarityChecks";
  C1?: "unchecked" | "ok" | "warning" | "blocked";
  C2?: "unchecked" | "ok" | "warning" | "blocked";
  C3?: "unchecked" | "ok" | "warning" | "blocked";
  C4?: "unchecked" | "ok" | "warning" | "blocked";
  C5?: "unchecked" | "ok" | "warning" | "blocked";
  C6?: "unchecked" | "ok" | "warning" | "blocked";
  C7?: "unchecked" | "ok" | "warning" | "blocked";
  C8?: "unchecked" | "ok" | "warning" | "blocked";
  C9?: "unchecked" | "ok" | "warning" | "blocked";
  C10?: "unchecked" | "ok" | "warning" | "blocked";
  C11?: "unchecked" | "ok" | "warning" | "blocked";
};

export type ReferenceItem = {
  _type: "referenceItem";
  label?: string;
  url?: string;
  publisher?: string;
  year?: number;
};

export type VideoEmbed = {
  _type: "videoEmbed";
  provider?: "youtube" | "vimeo";
  url?: string;
  title?: string;
  transcript?: string;
  caption?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithCaption = {
  _type: "imageWithCaption";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  credit?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithCaption)
  | ({
      _key: string;
    } & VideoEmbed)
>;

export type ClusterReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cluster";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type MedicalReviewerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "medicalReviewer";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  cluster?: ClusterReference;
  contentFormat?: "article" | "pillar";
  featuredImage?: ImageWithCaption;
  body?: PortableText;
  author?: AuthorReference;
  reviewedBy?: MedicalReviewerReference;
  reviewDate?: string;
  nextReviewDate?: string;
  editorialTier?: "standard" | "elevated" | "sensitive";
  references?: Array<
    {
      _key: string;
    } & ReferenceItem
  >;
  legalReviewed?: boolean;
  clarityChecks?: ClarityChecks;
  clarityTestDone?: boolean;
  clarityTestNotes?: string;
  seo?: Seo;
};

export type MedicalReviewer = {
  _id: string;
  _type: "medicalReviewer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  credentials?: string;
  specialty?: string;
  institutionNote?: string;
  bio?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  credentials?: string;
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Cluster = {
  _id: string;
  _type: "cluster";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  intro?: string;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Seo
  | ClarityChecks
  | ReferenceItem
  | VideoEmbed
  | SanityImageAssetReference
  | ImageWithCaption
  | PortableText
  | ClusterReference
  | AuthorReference
  | MedicalReviewerReference
  | Article
  | MedicalReviewer
  | Slug
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Cluster
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/articles.ts
// Variable: articlesByClusterQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0 && cluster->slug.current == $cluster]    | order(reviewDate desc) {      _id,      title,      "slug": slug.current,      excerpt,      reviewDate,      "cluster": cluster->{ title, "slug": slug.current },        "hasUsableBody": coalesce(    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,    false  )    }
export type ArticlesByClusterQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  reviewDate: string | null;
  cluster: {
    title: string | null;
    slug: string | null;
  } | null;
  hasUsableBody: boolean | false;
}>;

// Source: src/sanity/queries/articles.ts
// Variable: recentlyReviewedArticlesQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0] | order(reviewDate desc)[0...4] {    _id,    title,    "slug": slug.current,    excerpt,    reviewDate,    "cluster": cluster->{ title, "slug": slug.current },      "featuredImage": featuredImage{    alt,    caption,    credit,    crop,    hotspot,    asset->{      _id,      "dimensions": metadata.dimensions{ width, height }    }  },      "hasUsableBody": coalesce(    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,    false  )  }
export type RecentlyReviewedArticlesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  reviewDate: string | null;
  cluster: {
    title: string | null;
    slug: string | null;
  } | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      dimensions: {
        width: number | null;
        height: number | null;
      } | null;
    } | null;
  } | null;
  hasUsableBody: boolean | false;
}>;

// Source: src/sanity/queries/articles.ts
// Variable: articleBySlugQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0    && slug.current == $slug    && cluster->slug.current == $cluster][0] {        _id,  title,  "slug": slug.current,  excerpt,  contentFormat,  editorialTier,    "featuredImage": featuredImage{    alt,    caption,    credit,    crop,    hotspot,    asset->{      _id,      "dimensions": metadata.dimensions{ width, height }    }  },  body,  reviewDate,  nextReviewDate,  "cluster": cluster->{ title, "slug": slug.current },  "author": author->{ name, credentials, "slug": slug.current },  "reviewer": reviewedBy->{ name, credentials, specialty, institutionNote },  references[]{ label, url, publisher, year },  seo    }
export type ArticleBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  contentFormat: "article" | "pillar" | null;
  editorialTier: "elevated" | "sensitive" | "standard" | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      dimensions: {
        width: number | null;
        height: number | null;
      } | null;
    } | null;
  } | null;
  body: PortableText | null;
  reviewDate: string | null;
  nextReviewDate: string | null;
  cluster: {
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    name: string | null;
    credentials: string | null;
    slug: string | null;
  } | null;
  reviewer: {
    name: string | null;
    credentials: string | null;
    specialty: string | null;
    institutionNote: string | null;
  } | null;
  references: Array<{
    label: string | null;
    url: string | null;
    publisher: string | null;
    year: number | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries/articles.ts
// Variable: articleBySlugOnlyQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0 && slug.current == $slug][0] {        _id,  title,  "slug": slug.current,  excerpt,  contentFormat,  editorialTier,    "featuredImage": featuredImage{    alt,    caption,    credit,    crop,    hotspot,    asset->{      _id,      "dimensions": metadata.dimensions{ width, height }    }  },  body,  reviewDate,  nextReviewDate,  "cluster": cluster->{ title, "slug": slug.current },  "author": author->{ name, credentials, "slug": slug.current },  "reviewer": reviewedBy->{ name, credentials, specialty, institutionNote },  references[]{ label, url, publisher, year },  seo    }
export type ArticleBySlugOnlyQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  contentFormat: "article" | "pillar" | null;
  editorialTier: "elevated" | "sensitive" | "standard" | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      dimensions: {
        width: number | null;
        height: number | null;
      } | null;
    } | null;
  } | null;
  body: PortableText | null;
  reviewDate: string | null;
  nextReviewDate: string | null;
  cluster: {
    title: string | null;
    slug: string | null;
  } | null;
  author: {
    name: string | null;
    credentials: string | null;
    slug: string | null;
  } | null;
  reviewer: {
    name: string | null;
    credentials: string | null;
    specialty: string | null;
    institutionNote: string | null;
  } | null;
  references: Array<{
    label: string | null;
    url: string | null;
    publisher: string | null;
    year: number | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: src/sanity/queries/articles.ts
// Variable: sitemapArticlesQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0] | order(reviewDate desc) {    _id,    _updatedAt,    title,    "slug": slug.current,    excerpt,    reviewDate,    "cluster": cluster->{ title, "slug": slug.current },      "featuredImage": featuredImage{    alt,    caption,    credit,    crop,    hotspot,    asset->{      _id,      "dimensions": metadata.dimensions{ width, height }    }  },      "hasUsableBody": coalesce(    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,    false  )  }
export type SitemapArticlesQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  reviewDate: string | null;
  cluster: {
    title: string | null;
    slug: string | null;
  } | null;
  featuredImage: {
    alt: string | null;
    caption: string | null;
    credit: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
    asset: {
      _id: string;
      dimensions: {
        width: number | null;
        height: number | null;
      } | null;
    } | null;
  } | null;
  hasUsableBody: boolean | false;
}>;

// Source: src/sanity/queries/articles.ts
// Variable: publishableArticleSlugsQuery
// Query: *[  _type == "article"  && !(_id in path("drafts.**"))  && defined(author)  && defined(reviewedBy)  && defined(reviewDate)  && count(references) > 0] {    "slug": slug.current,    "cluster": cluster->slug.current  }
export type PublishableArticleSlugsQueryResult = Array<{
  slug: string | null;
  cluster: string | null;
}>;

// Source: src/sanity/queries/clusters.ts
// Variable: allClustersQuery
// Query: *[_type == "cluster" && !(_id in path("drafts.**"))] | order(order asc, title asc) {    _id,    _updatedAt,    title,    "slug": slug.current,    intro,    order  }
export type AllClustersQueryResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  intro: string | null;
  order: number | null;
}>;

// Source: src/sanity/queries/clusters.ts
// Variable: clusterBySlugQuery
// Query: *[_type == "cluster"    && slug.current == $cluster    && !(_id in path("drafts.**"))][0] {    _id,    title,    "slug": slug.current,    intro,    order  }
export type ClusterBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  intro: string | null;
  order: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n && cluster->slug.current == $cluster]\n    | order(reviewDate desc) {\n      _id,\n      title,\n      "slug": slug.current,\n      excerpt,\n      reviewDate,\n      "cluster": cluster->{ title, "slug": slug.current },\n      \n  "hasUsableBody": coalesce(\n    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,\n    false\n  )\n\n    }\n': ArticlesByClusterQueryResult;
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n] | order(reviewDate desc)[0...4] {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    reviewDate,\n    "cluster": cluster->{ title, "slug": slug.current },\n    \n  "featuredImage": featuredImage{\n    alt,\n    caption,\n    credit,\n    crop,\n    hotspot,\n    asset->{\n      _id,\n      "dimensions": metadata.dimensions{ width, height }\n    }\n  }\n,\n    \n  "hasUsableBody": coalesce(\n    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,\n    false\n  )\n\n  }\n': RecentlyReviewedArticlesQueryResult;
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n\n    && slug.current == $slug\n    && cluster->slug.current == $cluster][0] {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  contentFormat,\n  editorialTier,\n  \n  "featuredImage": featuredImage{\n    alt,\n    caption,\n    credit,\n    crop,\n    hotspot,\n    asset->{\n      _id,\n      "dimensions": metadata.dimensions{ width, height }\n    }\n  }\n,\n  body,\n  reviewDate,\n  nextReviewDate,\n  "cluster": cluster->{ title, "slug": slug.current },\n  "author": author->{ name, credentials, "slug": slug.current },\n  "reviewer": reviewedBy->{ name, credentials, specialty, institutionNote },\n  references[]{ label, url, publisher, year },\n  seo\n\n    }\n': ArticleBySlugQueryResult;
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n && slug.current == $slug][0] {\n      \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  contentFormat,\n  editorialTier,\n  \n  "featuredImage": featuredImage{\n    alt,\n    caption,\n    credit,\n    crop,\n    hotspot,\n    asset->{\n      _id,\n      "dimensions": metadata.dimensions{ width, height }\n    }\n  }\n,\n  body,\n  reviewDate,\n  nextReviewDate,\n  "cluster": cluster->{ title, "slug": slug.current },\n  "author": author->{ name, credentials, "slug": slug.current },\n  "reviewer": reviewedBy->{ name, credentials, specialty, institutionNote },\n  references[]{ label, url, publisher, year },\n  seo\n\n    }\n': ArticleBySlugOnlyQueryResult;
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n] | order(reviewDate desc) {\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    excerpt,\n    reviewDate,\n    "cluster": cluster->{ title, "slug": slug.current },\n    \n  "featuredImage": featuredImage{\n    alt,\n    caption,\n    credit,\n    crop,\n    hotspot,\n    asset->{\n      _id,\n      "dimensions": metadata.dimensions{ width, height }\n    }\n  }\n,\n    \n  "hasUsableBody": coalesce(\n    count(body[_type == "block" && count(children[defined(text) && text != ""]) > 0]) > 0,\n    false\n  )\n\n  }\n': SitemapArticlesQueryResult;
    '\n  *[\n  _type == "article"\n  && !(_id in path("drafts.**"))\n  && defined(author)\n  && defined(reviewedBy)\n  && defined(reviewDate)\n  && count(references) > 0\n] {\n    "slug": slug.current,\n    "cluster": cluster->slug.current\n  }\n': PublishableArticleSlugsQueryResult;
    '\n  *[_type == "cluster" && !(_id in path("drafts.**"))] | order(order asc, title asc) {\n    _id,\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    intro,\n    order\n  }\n': AllClustersQueryResult;
    '\n  *[_type == "cluster"\n    && slug.current == $cluster\n    && !(_id in path("drafts.**"))][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    intro,\n    order\n  }\n': ClusterBySlugQueryResult;
  }
}
